// src/shared/lib/mock-data.ts

export const mockEvents = [
  {
    id: '1',
    title: 'Monthly Mixer at The Station',
    slug: 'november-mixer-station',
    eventType: 'mixer',
    date: new Date('2024-11-21'),
    startTime: '5:30 PM',
    endTime: '7:30 PM',
    location: 'The Station SLO',
    description:
      "Join us for November's mixer at SLO's newest rooftop venue. Network with 500+ young professionals while enjoying sunset views.",
    image: '/images/events/mixer-station.jpg',
    pricing: {
      member: 0,
      nonMember: 10,
    },
    capacity: 100,
    attendees: 47,
    featured: true,
  },
  {
    id: '2',
    title: 'Professional Development: LinkedIn Optimization',
    slug: 'linkedin-workshop',
    eventType: 'professional',
    date: new Date('2024-11-14'),
    startTime: '6:00 PM',
    endTime: '7:30 PM',
    location: 'SLO Chamber of Commerce',
    description: 'Learn how to optimize your LinkedIn profile for maximum visibility and networking success.',
    image: '/images/events/linkedin-workshop.jpg',
    pricing: {
      member: 0,
      nonMember: 25,
    },
    capacity: 50,
    attendees: 32,
    featured: true,
  },
  {
    id: '3',
    title: 'Volunteer Saturday: Food Bank',
    slug: 'food-bank-november',
    eventType: 'volunteer',
    date: new Date('2024-11-30'),
    startTime: '9:00 AM',
    endTime: '12:00 PM',
    location: 'SLO Food Bank',
    description: 'Give back to the community by helping sort and distribute food to families in need.',
    image: '/images/events/food-bank.jpg',
    pricing: {
      member: 0,
      nonMember: 0,
    },
    capacity: 30,
    attendees: 18,
    featured: true,
  },
];

export const mockMembers = [
  {
    id: '1',
    firstName: 'Sarah',
    lastName: 'Chen',
    email: 'sarah.chen@example.com',
    title: 'Marketing Manager',
    company: 'MindBody',
    membershipType: 'annual',
    joinDate: new Date('2023-03-15'),
    profileImage: '/images/members/sarah-chen.jpg',
  },
  {
    id: '2',
    firstName: 'Michael',
    lastName: 'Rodriguez',
    email: 'michael.r@example.com',
    title: 'Senior Project Manager',
    company: 'RRM Design Group',
    membershipType: 'annual',
    joinDate: new Date('2022-01-10'),
    profileImage: '/images/members/michael-rodriguez.jpg',
  },
];

export const mockBoardMembers = [
  {
    id: '1',
    firstName: 'Marie',
    lastName: 'Perez',
    position: 'President',
    title: 'Manager',
    company: 'Coach',
    email: 'info@ypng.org',
    bio: "Marie, a Master's graduate in English Literature, brings a unique mix of education, management experience, and community-building to YPNG's board. As a substitute teacher in multiple school districts, she's passionate about education and community connection. Currently pursuing her teaching credential, Marie is all about expanding membership, fostering meaningful relationships, and diversifying group activities. Whether she's organizing engaging events or helping others level up in their careers, she's dedicated to making an impact.  Off the clock, you'll find her reading, writing, or hitting the softball and golf fields—bringing the same energy to the game as she does to YPNG!",
    committee: 'Executive, Events, Marketing',
    term: '2024-2026',
    profileImage: '/board-members/marie.jpg',
    linkedIn: 'https://linkedin.com/in/marieperez',
  },
  {
    id: '2',
    firstName: 'Gabriel',
    lastName: 'Schlaefer',
    position: 'Vice President',
    title: 'Real Estate Agent',
    company: 'Slo Real Estate',
    email: 'vicepresident@ypng.org',
    bio: "Gabriel was born in Sacramento and spent six years living and working in Japan after graduating from CSU Sacramento with a degree in business administration. He relocated to the Central Coast in 2024, having fallen in love with the Central Coast while visiting his family. As Vice President of YPNG, Gabriel is passionate about uncovering new volunteer opportunities and fostering positive connections with our community. Outside of his professional pursuits, he enjoys social dancing, board games, surfing, and savoring the myriad other experiences the 'coast with the most' has to offer.",
    committee: 'Executive, Events',
    term: '2024-2026',
    profileImage: '/board-members/gabe.jpg',
    linkedIn: 'https://linkedin.com/in/gabrielschlaefer',
  },
  {
    id: '3',
    firstName: 'Analiese',
    lastName: 'Scrivano',
    position: 'Secretary',
    title: 'Coordinator',
    company: 'Crop Science',
    email: 'secretary@ypng.org',
    bio: 'Analiese joined YPNG after seeing a group of people in matching t-shirts celebrating Taco Tuesday before their softball game.  Joining a softball team got her hooked on the group and crazy enough to be a coach for a few seasons.  She enjoys attending socials and hikes meeting new and regular YPNG members to chat. She works as a coordinator for a horticultural breeding program with her degree in Crop Science from Cal Poly.  Her hobbies include teaching partner acrobatics, running a local diabetes support group, hiking, reading, and dancing.',
    committee: 'Executive, Events',
    term: '2024-2026',
    profileImage: '/board-members/analiese.jpg',
    linkedIn: 'https://linkedin.com/in/analiesescrivano',
  },
  {
    id: '4',
    firstName: 'Brian',
    lastName: 'Coleman',
    position: 'Treasurer',
    title: 'Finance Manager',
    company: 'Company',
    email: 'treasurer@ypng.org',
    bio: 'Brian is a finance manager with a passion for helping others achieve their financial goals. He is dedicated to providing sound financial advice and guidance to YPNG members.',
    committee: 'Executive',
    term: '2024-2026',
    profileImage: '/board-members/brian.jpg',
    linkedIn: 'https://linkedin.com/in/briancoleman',
  },
  {
    id: '5',
    firstName: 'Chintan',
    lastName: 'Desai',
    position: 'Marketing Chair',
    title: 'Founder',
    company: 'Company',
    email: 'marketing@ypng.org',
    bio: "Chintan Desai grew up in the bright light of America, in San Luis Obispo, California, the son of Indian immigrant parents. He attended the University of California, Davis for his undergraduate degree, where he studied Political Science. He joined Teach For America\'s 2010 corps and worked as a fifth-grade social studies teacher for two years at KIPP Delta Public Schools, located in the rural Arkansas Delta town of Helena. He spent nearly a decade in Arkansas. He has held a variety of roles in the education, non-profit, and political fields, including serving as the Democratic nominee for U.S. Congress in Arkansas's First District in 2018. Chintan recently moved back to the San Luis Obispo area and is looking forward to getting more involved in the community.",
    committee: 'Marketing, Events',
    term: '2024-2026',
    profileImage: '/board-members/chintan.jpg',
    linkedIn: 'https://linkedin.com/in/chintandesai',
  },
  {
    id: '6',
    firstName: 'Mickey',
    lastName: 'Malotte',
    position: 'Volunteer Chair',
    title: 'Software Developer',
    company: 'Latitude Digital',
    email: 'community@ypng.org',
    bio: "Mickey is a software developer and music producer with nearly a decade of experience building software and leading collaborative projects. He's also a graduate of the National Outdoor Leadership School, where he completed a six-month backcountry leadership expedition. These diverse experiences—blending creativity, problem-solving, and people-first leadership—shape his approach as Volunteer Chair for YPNG. Grounded in values of presence, kindness, and genuine connection, Mickey is passionate about creating meaningful opportunities for members to engage, grow, and make a positive impact together.",
    committee: 'Volunteer, Community Outreach, Events',
    term: '2024-2026',
    profileImage: '/board-members/mickey.jpg',
    linkedIn: 'https://linkedin.com/in/mickeymalotte',
  },
];

export const mockStats = {
  members: 500,
  events: 1200,
  volunteerHours: 10000,
  raised: 250000,
};
